### PR TITLE
Added ETA to status

### PR DESCRIPTION
**Pull request by Abraxos**
I thought this program could use an ETA for estimating how long a given transfer should take, and coded up something rough. Please let me know what you think, feedback is welcome.

### CODE REVIEW

**Comment by laktak** [comment]
Thank you. I haven't tried your patch yet so I am undecided. The problem I see is that the ETA will constantly change while rsync is scanning (and it is very lazy in that regard). Doesn't the value jump around a lot?

rsync includes an estimate though I don't remember if it is per file. Have you checked the timing variable?

**Comment by Abraxos** [comment]
Oh man, I am so sorry about the delay, I was traveling and missed the notification.

> Doesn't the value jump around a lot?

In my experience, it jumps around in the first few seconds and then stabilizes to a pretty consistent value. I recommend checking this for yourself given that it might behave differently on someone else's system

> rsync includes an estimate though I don't remember if it is per file. Have you checked the timing variable?

Rsync estimates are per file last time I checked

**Comment by Abraxos** [comment]
So, have you had a chance to review the changes?

**Comment by Abraxos** [comment]
Checking in, any updates/opinions/feedback?

**Comment by laktak** [comment]
I have checked your PR (doing rsync over ssh with a few thousand files from a server) but I do not see any valid ETAs. rsync does not even finish scanning the server file structure until the transfer is almost complete - so I don't think it is even possible to show an ETA for this case.

I think it may be possible when you only have a few large files and rsync is able do a full scan but this is not true for all use cases.

I'm sorry for leaving this open for so long. If you still would like to improve upon this I would suggest only showing the ETA column if the scan is finished - assuming that it is then possible to show a realistic estimate.

**Pull request closed without merging**
